CREATE TABLE IF NOT EXISTS PUBLIC.FILM (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50) NOT NULL,
	DESCRIPTION CHARACTER VARYING(200),
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER,
	RATING_ID INTEGER NOT NULL,
	RATE INTEGER,
	CONSTRAINT FILM_PK PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC.FR_USER (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING(50) NOT NULL,
	LOGIN CHARACTER VARYING(50) NOT NULL,
	NAME CHARACTER VARYING(50),
	BIRTHDAY DATE,
	CONSTRAINT USER_PK PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
	USER_ID INTEGER NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	STATUS INTEGER NOT NULL,
	CONSTRAINT FRIENDS_PK PRIMARY KEY (USER_ID,FRIEND_ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC.LIKE_USER (
	FILM_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	CONSTRAINT LIKE_USER_PK PRIMARY KEY (FILM_ID,USER_ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC.RATING (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT RATING_PK PRIMARY KEY (ID)
);


